name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Backend Config
        run: |
          cat << EOF > terraform/backend.tf
          terraform {
            backend "s3" {
              bucket = "tripplescale-tf-backend"
              key    = "terraform.tfstate"
              region = "${{ secrets.AWS_REGION }}"
            }
          }
          EOF

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve
